# Cert Manager
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  smoothiemoni.simplon-duna.space
spec:
  dnsNames:
  - prometheus.eisi-dune.eu
  - grafana.eisi-dune.eu
  - loki.eisi-dune.eu
  issuerRef:
    name: letsencrypt
    kind: Issuer
  secretName: secret-tlsmoni