apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: workshop
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi-workshop
  resources:
    requests:
      storage: 1Gi
