# Issuer => Let’s Encrypt (certificats automatiques)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
spec:
  acme:
    email: dunvaelleroux@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # https://acme-v02.api.letsencrypt.org/directory ORIGINAL
    # https://acme-staging-v02.api.letsencrypt.org/directory TESTS
    # Email address used for ACME registration
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - http01:
          ingress:
            class: traefik
