version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: escape-game-front
    restart: unless-stopped
    environment:
      - NODE_ENV=production
